name: method_channel_ex
description: Alternative Flutter method channel.
version: 0.0.3
author: Yrom Wang <hi@yongrong.wang>
homepage: https://github.com/yrom/flutter_method_channel_ex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  executor: 
    git: https://git.bilibili.co/phoenix/dart-executor.git
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
 
